### ISSUE TITLE
Codes using Reflection crash under Wine

### ISSUE THREAD

**Issue by RibShark** [hedge-dev/HMMCodes#7]
Currently, codes using Reflection cause the game to crash when running under Wine. Tested on Sonic Origins with the Locked 30 FPS code, as well as the Original Remaster SFX Pack and Sonic CD Fix Timing/Restore SFX mod.

**Comment by Sajidur78** [comment]
It's possible that this issue was fixed on b79d9d5. Try updating community codes and check again.

**Comment by RibShark** [comment]
Unfortunately not, the issue is still occurring. The game window shows for a bit with a black screen before disappearing, but the process still seems to be active until it is killed by Steam by hitting quit on the client.

**Comment by Sajidur78** [comment]
Do you have any other info about the crash? Like any crash dumps or error log?

**Comment by RibShark** [comment]
Here is the proton log for the game: [steam-1794960.log](https://github.com/hedge-dev/HMMCodes/files/12566314/steam-1794960.log). No other logs are created and no errors are shown in the console output.

**Comment by RibShark** [comment]
Is there anything I can do to make progress on this issue? I am willing to try and debug it but I'm unsure how best to debug .NET software under Wine.

**Comment by DeaTh-G** [comment]
See https://github.com/thesupersonic16/HedgeModManager/issues/697 for further context.

**Comment by SolarNyan** [comment]
I can add that I and others are also running into HMM codes breaking on Linux. Anything gameplay related breaks on Desktop Linux, and Steam Deck is apparently worse according to recent posts on HMM's main repository Linux issue tracker: [https://github.com/thesupersonic16/HedgeModManager/issues/219#issuecomment-1800913211](url)

**Comment by SolarNyan** [comment]
Update: Could you try using Bottles' Steam integration feature to try and have it install dotnet40 and dotnet48 manually to your HHE2  game's prefix? Codes that were borking Frontiers are now working after doing this. [More info in my post on the main repo.](https://github.com/thesupersonic16/HedgeModManager/issues/219#issuecomment-1817726153)

**Comment by RibShark** [comment]
> Update: Could you try using Bottles' Steam integration feature to try and have it install dotnet40 and dotnet48 manually to your HHE2 game's prefix? Codes that were borking Frontiers are now working after doing this. [More info in my post on the main repo.](https://github.com/thesupersonic16/HedgeModManager/issues/219#issuecomment-1817726153)

Can confirm this worked., though I had to add the registry entry "HKLM\Software\Microsoft\.NETFramework\InstallRoot" to point to "C:\Windows\Microsoft.Net\Framework64\".

**Comment by ActualMandM** [comment]
> Do you have any other info about the crash? Like any crash dumps or error log?

I have a crash dump from Sonic Frontiers using my Stillness & Motion mod.
[ReflectionCrash.zip](https://github.com/hedge-dev/HMMCodes/files/13434817/ReflectionCrash.zip)
I'm also providing the profile INI and the generated Codes file.
